# Generated by Django 4.2 on 2023-05-13 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extract', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trg_address', models.TextField()),
                ('was_executed_before', models.BooleanField(default=False)),
                ('src_address_count', models.IntegerField(default=0)),
                ('amount', models.DecimalField(decimal_places=5, default=0.0, max_digits=8)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Rule',
        ),
    ]
