# Generated by Django 4.2 on 2023-05-13 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extract', '0003_extract_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extract',
            name='transaction',
            field=models.CharField(blank=True),
        ),
    ]
