# Generated by Django 4.2 on 2023-05-13 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extract', '0004_alter_extract_transaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extract',
            old_name='amount',
            new_name='BTC_amount',
        ),
        migrations.RenameField(
            model_name='extract',
            old_name='created',
            new_name='executed_on',
        ),
        migrations.RenameField(
            model_name='extract',
            old_name='src_address_count',
            new_name='source_address_count',
        ),
        migrations.RenameField(
            model_name='extract',
            old_name='trg_address',
            new_name='target_address',
        ),
    ]
