# Generated by Django 4.2 on 2023-05-15 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extract', '0005_rename_amount_extract_btc_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extract',
            name='transaction',
            field=models.CharField(blank=True, max_length=84),
        ),
    ]
