# Generated by Django 4.2 on 2023-05-15 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_productreview_rate_alter_review_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='comment',
            field=models.TextField(default='', max_length=1024),
        ),
    ]
