# Generated by Django 4.2 on 2023-05-15 18:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_productreview_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
