# Generated by Django 4.1.3 on 2023-03-22 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="address2",
        ),
    ]
