# Generated by Django 4.2 on 2023-04-29 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_shipped'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='transferred',
            field=models.BooleanField(default=False),
        ),
    ]
