# Generated by Django 4.2 on 2023-05-15 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_transferred'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
