#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE USER $BITCOIN_USER WITH PASSWORD '$BITCOIN_PASSWORD';
	CREATE DATABASE $BITCOIN_DB;
    ALTER DATABASE $BITCOIN_DB  OWNER TO $BITCOIN_USER;
	GRANT ALL PRIVILEGES ON DATABASE $BITCOIN_DB TO $BITCOIN_USER;
    GRANT ALL ON SCHEMA public TO $BITCOIN_USER;
EOSQL