# Generated by Django 4.1.3 on 2022-11-17 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Intent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_key", models.CharField(max_length=200)),
                ("payment_address", models.CharField(default="", max_length=100)),
                (
                    "paid_amount",
                    models.DecimalField(decimal_places=9, default=0.0, max_digits=10),
                ),
                ("total_amount", models.DecimalField(decimal_places=9, max_digits=10)),
                ("paid", models.BooleanField(default=False)),
                ("expired", models.BooleanField(default=False)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="intent_user",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Intents",
                "verbose_name_plural": "Intents",
            },
        ),
    ]
