# Generated by Django 4.1.3 on 2023-03-22 17:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="intent",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="intent",
            name="email",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="intent",
            name="order_key",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="intent",
            name="paid_amount",
            field=models.DecimalField(decimal_places=5, max_digits=8),
        ),
        migrations.AlterField(
            model_name="intent",
            name="total_amount",
            field=models.DecimalField(decimal_places=5, max_digits=8),
        ),
    ]
